name: Cron Demo

on:
  schedule:
    - cron: '*/5 * * * *'   # Every 5 minutes

  workflow_dispatch:        # Allows manual execution

jobs:
  show-time:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current Date and Time
        run: |
          echo "Workflow Triggered Successfully"
          echo "Current UTC Time:"
          date -u
          echo "Current System Time:"
          date
